sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    # notes: '[便笺](/notes/)'
    more: '[更多](/about/)'
  # widgets:
  #   default_layout: [welcome, recent]

comments:
  service: beaudar
  beaudar:
    repo: wejudging/blog-comments


footer:
  social:
     - icon: '<img src="/images/rss.svg"/>'
       url: https://weijiajin.com/atom.xml
     - icon: '<img src="/images/gmail.svg"/>'
       url: mailto:wejudging@gmail.com
     - icon: '<img src="/images/github.svg"/>'
       url: https://github.com/wejudging
     - icon: '<img src="/images/volantis.svg"/>'
       url: https://volantis.weijiajin.com
     - icon: '<img src="/images/youqinglianjie.svg"/>'
       url: https://weijiajin.com/friends/
     - icon: '<img src="/images/OneDrive.svg"/>'
       url: https://cloud.weijiajin.com

  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/blog/categories/)'
      - '[标签](https://weijiajin.com/blog/tags/)'
      - '[归档](https://weijiajin.com/blog/archives/)'
    '项目':
      - '[脚本](https://weijiajin.com/wiki/tags/脚本/)'
      - '[教育优惠](https://weijiajin.com/wiki/tags/教育优惠/)'
    '便笺':
      - '[友链](https://weijiajin.com/friends/)'
      - '[留言板](https://weijiajin.com/about/#comments)'
    '更多':
      - '[关于本站](https://weijiajin.com/about/)'
      - '[GitHub](https://github.com/wejudging)'
  content: |
     <hr><p align="center"><a href="https://aws.amazon.com/cn/campaigns/cloudfront"><img src="/images/内容分发-CloudFront-orange.svg" width="143" height="20" /></a>&nbsp&nbsp<a href="https://github.com/wejudging"><img src="/images/网站部署-GitHub-5DADE2.svg" width="119" height="20"/></a>&nbsp&nbsp<a href="https://hexo.io"><img src="/images/强力驱动-Hexo-blue.svg" width="111" height="20"/></a>&nbsp&nbsp<a href="https://cloudflare.com"><img src="/images/域名解析-CloudFlare-f38020.svg"></a></p>

article:
  # 分类颜色
  category_color:
    '折腾': '#DA0F47'
    '诗文': '#03a9f4'


plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn.staticfile.org/jquery/3.5.1/jquery.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: false # [hexo clean && hexo s] is required after changing this value.
    js: /js_css/lazyload.js
    transition: fade # blur, fade

  # preload
  preload:
    enable: false
    service: flying_pages # instant_page, flying_pages
    instant_page: /js_css/preload/instant_page.js
    flying_pages: /js_css/preload/flying_pages.js

  # 赫蹏 (Heti) - 专为中文网页内容设计的排版样式增强
  # https://github.com/sivan/heti
  heti:
    enable: false
    css: https://unpkg.com/heti/umd/heti.min.css
    js: https://unpkg.com/heti/umd/heti-addon.min.js

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: false
    js: /js_css/fancybox/umd.js
    css: /js_css/fancybox/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    selector: .swiper-slide img # 多个选择器用英文逗号隔开

style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: /images/rainbow64.webp
  codeblock:
    scrollbar: 4px

default:
  avatar: /images/3442075.svg
  link: /images/8f277b4ee0ecd.svg
  cover: /images/76b86c0226ffd.svg
  image: /images/2659360.svg
