sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[更多](/about/)'
  # widgets:
  #   default_layout: [welcome, recent]

comments:
  service: beaudar
  beaudar:
    repo: wejudging/blog-comments


footer:
  social:
     - icon: '<img src="https://shop.weijiajin.com/images/rss.svg"/>'
       url: https://weijiajin.com/atom.xml
     - icon: '<img src="https://shop.weijiajin.com/images/gmail.svg"/>'
       url: mailto:wejudging@gmail.com
     - icon: '<img src="https://shop.weijiajin.com/images/github.svg"/>'
       url: https://github.com/wejudging
     - icon: '<img src="https://shop.weijiajin.com/images/volantis.svg"/>'
       url: https://volantis.weijiajin.com
     - icon: '<img src="https://shop.weijiajin.com/images/resume.svg"/>'
       url: https://resume.weijiajin.com
     - icon: '<img src="https://shop.weijiajin.com/images/youqinglianjie.svg"/>'
       url: https://weijiajin.com/friends/
     - icon: '<img src="https://shop.weijiajin.com/images/OneDrive.svg"/>'
       url: https://onedrive.weijiajin.com

  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/blog/categories/)'
      - '[标签](/blog/tags/)'
      - '[归档](/blog/archives/)'
    '项目':
      - '[脚本](/wiki/tags/脚本/)'
      - '[笔记](/wiki/tags/笔记/)'
    '便笺':
      - '[友链](/friends/)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[关于本站](/about/)'
      - '[GitHub](https://github.com/wejudging)'
 

article:
  # 分类颜色
  category_color:
    '折腾': '#DA0F47'
    '诗文': '#03a9f4'


plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn.staticfile.org/jquery/3.5.1/jquery.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://shop.weijiajin.com/js_css/lazyload.js
    transition: fade # blur, fade

  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://shop.weijiajin.com/js_css/preload/instant_page.js
    flying_pages: https://shop.weijiajin.com/js_css/preload/flying_pages.js

  # 赫蹏 (Heti) - 专为中文网页内容设计的排版样式增强
  # https://github.com/sivan/heti
  heti:
    enable: true
    css: https://unpkg.com/heti/umd/heti.min.css
    js: https://unpkg.com/heti/umd/heti-addon.min.js

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: true
    js: https://shop.weijiajin.com/js_css/fancybox/umd.js
    css: https://shop.weijiajin.com/js_css/fancybox/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    selector: .swiper-slide img # 多个选择器用英文逗号隔开

style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: https://shop.weijiajin.com/images/rainbow64.webp
  codeblock:
    scrollbar: 4px

default:
  avatar: https://shop.weijiajin.com/images/3442075.svg
  link: https://shop.weijiajin.com/images/8f277b4ee0ecd.svg
  cover: https://shop.weijiajin.com/images/76b86c0226ffd.svg
  image: https://shop.weijiajin.com/images/2659360.svg
