sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[更多](/about/)'
  # widgets:
  #   default_layout: [welcome, recent]

comments:
  service: beaudar
  beaudar:
    repo: wejudging/blog-comments


footer:
  social:
     - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/25678f144c438.svg"/>'
       url: https://cdn.jsdelivr.net/gh/wejudging/wejudging.github.io@public/atom.xml
     - icon: '<img src="https://cdn.jsdelivr.net/gh/wejudging/wejudging.github.io/source/images/gmail.svg"/>'
       url: mailto:wejudging@gmail.com
     - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/08a41b181ce68.svg"/>'
       url: https://github.com/wejudging
     - icon: '<img src="https://cdn.jsdelivr.net/gh/wejudging/wejudging.github.io/source/images/volantis.svg"/>'
       url: https://volantis.weijiajin.com
     - icon: '<img src="https://cdn.jsdelivr.net/gh/wejudging/wejudging.github.io/source/images/resume.svg"/>'
       url: https://resume.weijiajin.com
     - icon: '<img src="https://cdn.jsdelivr.net/gh/wejudging/wejudging.github.io/source/images/youqinglianjie.svg"/>'
       url: https://weijiajin.com/friends/
     - icon: '<img src="https://cdn.jsdelivr.net/gh/wejudging/wejudging.github.io/source/images/OneDrive.svg"/>'
       url: https://onedrive.weijiajin.com

  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/blog/categories/)'
      - '[标签](/blog/tags/)'
      - '[归档](/blog/archives/)'
    '项目':
      - '[开源库](/wiki/tags/开源库/)'
      - '[实用脚本](/wiki/tags/实用脚本/)'
    '便笺':
      - '[友链](/friends/)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[关于本站](/about/)'
      - '[GitHub](https://github.com/wejudging)'
 


style:
  codeblock:
    scrollbar: 0px



article:
  # 分类颜色
  category_color:
    '折腾': '#DA0F47'
    '诗文': '#03a9f4'

