sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    more: '[更多](/about/)'
  # widgets:
  #   default_layout: [welcome, recent]

comments:
  service: beaudar
  beaudar:
    repo: wejudging/blog-comments