######## head tags ########
open_graph:
  enable: true
  twitter_id: # for open_graph meta


sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    friends: '[友链](/friends/)'
    about: '[关于](/about/)'
  widgets:
    index: [timeline] # for home/wiki/categories/tags/archives/404 pages
    page: [timeline] # for pages using 'layout:page'
    post: [toc, ghrepo, ghissues, related] # for pages using 'layout:post'
    wiki: [toc, ghrepo, ghissues, related] # for pages using 'layout:wiki'



comments:
  service: beaudar
  beaudar:
    repo: wejudging/blog-comments


footer:
  social:
     - icon: '<img src="/images/rss.svg"/>'
       url: /atom.xml
     - icon: '<img src="/images/gmail.svg"/>'
       url: mailto:wejudging@gmail.com
     - icon: '<img src="/images/github.svg"/>'
       url: https://github.com/wejudging
     - icon: '<img src="/images/volantis.svg"/>'
       url: https://volantis.weijiajin.com
     - icon: '<img src="/images/OneDrive.svg"/>'
       url: https://cloud.weijiajin.com

  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/categories/)'
      - '[标签](/tags/)'
      - '[归档](/archives/)'
    '项目':
      - '[脚本](/wiki/tags/脚本/)'
      - '[教育优惠](/wiki/tags/教育优惠/)'
    '友链':
      - '[友链](/friends/)'
      - '[留言板](/about/#comments)'
    '关于':
      - '[关于本站](/about/)'
      - '[GitHub](https://github.com/wejudging)'
  content: |
     <hr><p align="center"><a href="https://aws.amazon.com/cn/campaigns/cloudfront"><img src="/images/内容分发-CloudFront-orange.svg" width="143" height="20" /></a>&nbsp&nbsp<a href="https://github.com/wejudging"><img src="/images/网站部署-GitHub-5DADE2.svg" width="119" height="20"/></a>&nbsp&nbsp<a href="https://hexo.io"><img src="/images/强力驱动-Hexo-blue.svg" width="111" height="20"/></a>&nbsp&nbsp<a href="https://cloudflare.com"><img src="/images/域名解析-CloudFlare-f38020.svg"></a></p>



plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn.staticfile.org/jquery/3.5.1/jquery.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: false # [hexo clean && hexo s] is required after changing this value.
    js: /js_css/lazyload.js
    transition: blur # blur, fade

  scrollreveal:
    enable: true
    js: https://fastly.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 4px # 执行距离
    duration: 400 # ms # 执行时长
    interval: 100 # ms # 执行间隔（时间）
    scale: 0.1 # 0.1~1 # 执行方式（缩放）

  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: /js_css/preload/instant_page.js
    flying_pages: /js_css/preload/flying_pages.js

  # 赫蹏 (Heti) - 专为中文网页内容设计的排版样式增强
  # https://github.com/sivan/heti
  heti:
    enable: true
    css: https://unpkg.com/heti/umd/heti.min.css
    js: https://unpkg.com/heti/umd/heti-addon.min.js

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: false
    js: /js_css/fancybox/umd.js
    css: /js_css/fancybox/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    selector: .swiper-slide img # 多个选择器用英文逗号隔开


  # Katex - The fastest math typesetting library for the web
  # https://katex.org/docs/autorender.html
  # https://github.com/KaTeX/KaTeX
  # 使用 hexo-renderer-markdown-it-plus 作为公式渲染器：npm uninstall hexo-renderer-marked --save npm install hexo-renderer-markdown-it-plus --save
  katex:
    enable: true
    min_css: <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    min_js: <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    auto_render_min_js: <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"onload="renderMathInElement(document.body);"></script>



style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: /images/rainbow64.webp
  codeblock:
    scrollbar: 4px

default:
  avatar: /images/3442075.svg
  link: /images/8f277b4ee0ecd.svg
  cover: /images/76b86c0226ffd.svg
  image: /images/2659360.svg



######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面图片？
  auto_cover: true # search from https://source.unsplash.com/
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '折腾': '#DA0F47'
    '诗文': '#03a9f4'
  # 文章许可协议
  license: '本文采用[署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/)许可协议，转载请注明出处。'
  # 分享
  share: [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 5