sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[更多](/about/)'
  # widgets:
  #   default_layout: [welcome, recent]

comments:
  service: beaudar
  beaudar:
    repo: wejudging/blog-comments


footer:
  social:
     - icon: '<img src="/images/rss.svg"/>'
       url: https://weijiajin.com/atom.xml
     - icon: '<img src="/images/gmail.svg"/>'
       url: mailto:wejudging@gmail.com
     - icon: '<img src="/images/github.svg"/>'
       url: https://github.com/wejudging
     - icon: '<img src="/images/volantis.svg"/>'
       url: https://volantis.weijiajin.com
     - icon: '<img src="/images/resume.svg"/>'
       url: https://resume.weijiajin.com
     - icon: '<img src="/images/youqinglianjie.svg"/>'
       url: https://weijiajin.com/friends/
     - icon: '<img src="/images/OneDrive.svg"/>'
       url: https://onedrive.weijiajin.com

  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/blog/categories/)'
      - '[标签](/blog/tags/)'
      - '[归档](/blog/archives/)'
    '项目':
      - '[脚本](/wiki/tags/脚本/)'
      - '[笔记](/wiki/tags/笔记/)'
    '便笺':
      - '[友链](/friends/)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[关于本站](/about/)'
      - '[GitHub](https://github.com/wejudging)'
 


style:
  codeblock:
    scrollbar: 0px



article:
  # 分类颜色
  category_color:
    '折腾': '#DA0F47'
    '诗文': '#03a9f4'


plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn.staticfile.org/jquery/3.5.1/jquery.min.js

